"""Generate app/src/main/java/ir/simorgh/chess/Themes.kt from the desktop
app's gui/src/themes.ts, so the two apps offer the same themes with the same
values. Run from android/:  python tools/gen_themes.py
"""
import io, re, os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "..", "gui", "src", "themes.ts")
OUT = os.path.join(HERE, "..", "app", "src", "main", "java", "ir", "simorgh", "chess", "Themes.kt")

# Desktop token -> Kotlin palette field.
FIELDS = [
    ("bg", "bg"), ("bg-2", "trough"), ("surface", "surface"), ("surface-2", "surface2"),
    ("border", "border"), ("accent", "accent"), ("accent-dim", "accentDim"),
    ("on-accent", "onAccent"), ("on-accent-dim", "onAccentDim"),
    ("fg", "fg"), ("fg-dim", "fgDim"), ("muted", "muted"),
    ("ok", "ok"), ("warn", "warn"), ("danger", "danger"),
    ("light-sq", "lightSquare"), ("dark-sq", "darkSquare"),
    ("coord-on-light", "coordOnLight"), ("coord-on-dark", "coordOnDark"),
    ("sel", "selected"), ("last", "lastMove"),
]

def argb(css):
    css = css.strip()
    m = re.fullmatch(r"#([0-9a-fA-F]{6})", css)
    if m:
        return "0xFF" + m.group(1).upper()
    m = re.fullmatch(r"rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([\d.]+)\s*\)", css)
    if m:
        r, g, b = (int(m.group(i)) for i in (1, 2, 3))
        a = round(float(m.group(4)) * 255)
        return "0x%02X%02X%02X%02X" % (a, r, g, b)
    raise ValueError(f"unsupported colour {css!r}")

src = io.open(SRC, encoding="utf-8").read()
blocks = re.findall(
    r'id:\s*"(\w+)",\s*name:\s*\{\s*fa:\s*"([^"]+)",\s*en:\s*"([^"]+)"\s*\},\s*'
    r'scheme:\s*"(\w+)",\s*tokens:\s*\{(.*?)\n\s*\},', src, re.S)
assert blocks, "no themes parsed"

out = ['package ir.simorgh.chess', '',
       '// GENERATED by android/tools/gen_themes.py from gui/src/themes.ts.',
       '// Edit the themes there and regenerate; do not edit this file by hand.', '',
       'import androidx.compose.ui.graphics.Color', '',
       'data class Palette(',
       '    val id: String,', '    val nameFa: String,', '    val nameEn: String,', '    val light: Boolean,']
out += [f'    val {k}: Color,' for _, k in FIELDS]
out += [')', '', 'val THEMES: List<Palette> = listOf(']
for tid, fa, en, scheme, body in blocks:
    tokens = dict(re.findall(r'"([\w-]+)":\s*"([^"]+)"', body))
    out.append('    Palette(')
    out.append(f'        id = "{tid}", nameFa = "{fa}", nameEn = "{en}", light = {str(scheme == "light").lower()},')
    for tok, k in FIELDS:
        out.append(f'        {k} = Color({argb(tokens[tok])}),')
    out.append('    ),')
out += [')', '']
io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out))
print(f"wrote {len(blocks)} themes -> {os.path.relpath(OUT)}")
